### ISSUE TITLE
Feedback from Fraunhofer

### ISSUE THREAD

**Issue by philieeas** [seifou23i/Grid2Bench#11]
- `pip install poetry` in README.md/Setup Virtualenv(optional) would be nice
- `poetry install` was nice and easy 👍
- The example in *Usage* does not show/explain how to generate the run/plot data ❓
- MazeRL_Agent data not included in package: `FileNotFoundError: [Errno 2] No such file or directory: '../data/input/MazeRL_Agent'`
- Load agent results takes a lot of time ⏲(Probably hard for you to fix)️
- `col=3` for some functions seems unnessesariy since the agents are stored in the `AgentAnalytics` class already

**Comment by seifou23i** [comment]
- All feedback have been taken into consideration
