### ISSUE TITLE
Improving getting started notebook

### ISSUE THREAD

**Issue by marota** [seifou23i/Grid2Bench#7]
Use conf.ini in the notebook to get the necessary configuration paths, to invite the user to use this.
There could be a specific conf.ini to test the notebook

We should also include the utilities to inspect the dataframes of actions, etc ... We only see plots for now

**Comment by seifou23i** [comment]
- The config file is linked to the notebook
- Some utility functions added to the notebook, you can find the detailed utility function documentation in : https://grid2bench.readthedocs.io/en/latest/grid2bench.html#module-grid2bench.EpisodesDataTransformer
